// <auto-generated />
namespace MVC4ScaffoldingEFMigrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddMiddleName : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203301747108_AddMiddleName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7TQBC+I/EO1p7gQDYUhKByikrSoAjSVrj0vrHH6Yr9Md51lTwbBx6JV2DW/7GbpGkRcLPXM998OzvfzPrXj5/++5UU3i2khms1Ii8HQ+KBCnXE1XJEMhu/eEvenzx94p9FcuVdV3ZHzg49lRmRG2uTY0pNeAOSmYHkYaqNju0g1JKySNOj4fAtfTmkgBAEsTzP/5IpyyXkL/g61iqExGZMzHUEwpTr+CXIUb1zJsEkLIQRmV+PXwchi2MtHMmz6ZwvU2aRlhkU3sQ7FZwhswBEfCDN4TtHk9QEkMIZUrXrq3UCOY0RucQsaNW2QatPsN5YwKXLVCeQ2vUXiDc8ZxPi0U1v2nWvnXuejsiIzJR9dUS880wIthC4EDNhgHjJm+PA6hQ+ggLMCkSXzFpI8chmEeQbKRNynLy5X07e0eGRywllSmmbJ7pHv0N2ylNj3WPFNrApHhXxpnwF0WdQS3tTM56zVbWCj8T7qjiWHzrZNIP2Dov33ZE/s38UeM6jSMBfCO3Tph77VYpCsozj0Ve0tovFmcLKdsq4gAnA1nWnE4EUmqCFrAalCO7kVrNodEwLIVeCp1sU789ZkiDRVgcoV7ygkP/4RXC4pGWBQUNzh7JrtnUkFBBbQucrhkameWlPmGUL5g5yHMme2cNzXhHYSH23qzQnUZm7573HXfbGwV3Nq53nKW5dYqfIswA1tbu7XumKIQVLt3assRaZVLs74C6kVjtpQ7WW74/VNIg2VLN6f6S24ttY7fU+mk87ee4eL+2db2dSdKtll/66JnX0Wocdvfll7e8fwz0xFCbEwzTd8sgJIVgbC3LgDAbBdzEWHPfbGMyZ4jEYe6W/gbtSoFYfPrnrKWVMJP7/8c1dIvYO6t50P3DsqluWhjcsfSbZ6vljR+mjwPrj8QC4w0Zev0vvm3DFINs64YrCHpFooZF8QbIaiw+cfn2V+bR9JfYnYPiygXAXZAWha+QNaGUzU7Gu0o3bajOqTLqnAZZFmJ3T1PKYhRY/h2BMfl25ZiJDkzO5gGimLjKbZPbUGJALsW7v16e74+cjfpOzf5Hko+hPbAFpctwCXKgPGRdRzXvaF8o2CFcopfqQFV7XEG65rpHOtbonUJm+CSSgnHavQCYCwcyFCtgtbOe2P4ebGfMnnOE8l+0MFislk4DJjbLEAG2PJp77o6Pul+7kN4oNf6QEDgAA"; }
        }
    }
}
