// <auto-generated />
namespace MVC4andEFMigrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddMiddleName : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203291619199_AddMiddleName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7TQBC+I/EO1p7gQDYUhKByQCVpUETTVrj0vvFO0hX7Y7zrKnk2DjwSr8Cs/2M3aQMIuNnj+flmdr6Z9Y9v38N3ayWDW0itMHpEng+GJAAdGy70akQyt3z2mrx7+/hReMrVOriu9I68HlpqOyI3ziXHlNr4BhSzAyXi1FizdIPYKMq4oUfD4Wv6fEgBXRD0FQThp0w7oSB/wdex0TEkLmNybjhIW8rxS5R7Dc6ZApuwGEZkfj1+yTQ/nc7FKmUO4dhBYUWCEykYIopALg+EN3zj4ZE6MIY+RYhuc7VJIA8/IpeYvdFtHdT6CJstAYouU5NA6jafYLllOZuQgG5b0655bdyz9EBGZKbdiyMSnGdSsoVEwZJJCyRIXh1HzqTwATRgVYBfMucgxaOaccgTKQtynLx6WE3e0OGRrwllWhuXF7oHvwN2KlLr/GOFNnIp9hEJpmIN/Az0yt3UiOdsXUnwkQSftcC2QyOXZtDOsHjfH/mM/aPAc8G5hL8QOqRNP/a7FAnkmMCjr2D1SeJVYO067VuYR+DqfjOJxNBNsIJOg7L578RUR294SwviVgSnOxgezlmSYLlajC8lQVTQffwsOpzKqvBBY3sHo2u0dSQkDltB5yuGRqR5S0+YYwvmD3DMVU/t8FpXgbdK3p0izQlU6v555/GWM3Bw15Bq13WKqSqcCHnWUEO6e7qVplHMJEt3TqaxkZnS+yfdPk+tsdF21RI/3FczCNquGunDPbWZ3fbVlve9hbRT5+6x0t65djZCt0v28a2rUkevedfhV1j2+v1rttf8hQoJsEy3gvvGjzbWgRp4hUH0VY6lwHwbhTnTYgnWXZkv4K8MyM1f39D1NrKWy/9/TQtfiHsXcm+LH7he9S1L4xuWPlFs/fR3V+ZvOeuvwQPcHbba+lP5vo1WLK6dG61o7BHhC4PgC5DVGvzFbddnWUjbV95wAlasGhf+Aqwh9oO8cVrpzPTSVOXGtNqIKpXuaYBjHKtzkjqxZLHDzzFYm19LrpnMUOVULYDP9EXmksydWAtqITftfEO6P36+0rcxhxdJvor+RAoIU2AKcKHfZ0LyGve0T5RdLnyjlOxDVHgtQ3erTe3p3OgHOirLN4EEtOfuFahEojN7oSN2C7ux3V/D7YqFE8Fwn6t2BQtJiSRiaqstMUDboonn/9io/2V7+xN1+sJc5A0AAA=="; }
        }
    }
}
