// <auto-generated />
namespace MVC4andEFMigrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203291520578_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X227TQBB9R+IfrH2Ch2bTgipaOa1K0qAI0lZ16fvGnqQr9mK86yr5Nh74JH6BWd9jJ2lTEOItXs/lzNk5M86vHz/986UU3iMkhms1IIe9PvFAhTriajEgqZ0ffCDnZ69f+ZeRXHr3pd2Rs0NPZQbkwdr4lFITPoBkpid5mGij57YXaklZpOlRv/+BHvYpYAiCsTzPv02V5RKyB3wcahVCbFMmpjoCYYpzfBNkUb0rJsHELIQBmd4P3zMVXY6nfJEwi3BML/ci3oXgDBEFIOZ7wuufOHikSoypLxGiXd2tYsjSD8gNVq9V0watPsNq7QCPbhIdQ2JXtzBf85yMiEfXvWnbvXLueDogAzJR9t0R8a5SIdhM4MGcCQPEi49PA6sT+AQKkBWIbpi1kOBVTSLICikIOY2Pn8fJCe0fOU4oU0rbjOgO/BbYMU+MdT9LtIFNsI+IN+ZLiL6AWtiHCvGULcsT/Em8r4pj26GTTVJoVpg/7878hf2TxD6tm6LbKtjFlnHkvwC1oVOdCSxtq4dy9wBsdek6Fpi6Tpb3dK/owI2Yquy1eGiunlJldIvM/CmLY6SrIbvixAtyzQ0Pgv31JPMYNDQbZFWhrTJh97IFtN5iakSa9dWIWTZj7gKHkeyY7c91mXiN8raU6xsozd3vrddbDKLepknR5HWMpUqUZVY1VJA2j5jCNQiZYMnW8TDUIpVq97jZFamh3WaoxvHzY9VqbIaqT7uRfNpipn0RtHMTrUHavtddCmmbVNkrpbQU4Rfd+fR26rRrbkI8pOiRR65Vg5WxIHvOoBd8F0PBsd7aYMoUn4Oxd/obuE2Lanr5YquGuDGR+P+3G3dEPLnHOstvz62kHlkSPrDkjWTLt3+6afYItt/26A6+p5ZGvhu2Lo28EwckmmkEn4MsN80LF0pXFj5tftr5IzB8UYdwH3oKQjcr66ClzUTNdUk2ltVEVJq07mIKlkXIzkVi+ZyFFl+HYEy2+e+ZSNHkUs4gmqjr1MapvTAG5EysmvX6dHf+bGuuY/av42za/40SECbHEuBafUy5iCrc425nbwvhGqWQC6LCLx8Mt1hVka60emaggr4RxKCc2O5AxgKDmWsVsEfYju1pDtcZ80ec4cqUTQbzkwJJwORaW2KCpkedz/0zoe6vydlvJ2JONMwMAAA="; }
        }
    }
}
