// <auto-generated />
namespace MVC4ScaffoldingEFMigrations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203301739135_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X227TQBB9R+IfrH2CB7JpQRVUDqgkDYpo2gqXvm/scbpiL8a7rpJv44FP4heY9T12kzQFId7i9VzOnpkz4/z68dP/sJLCu4fUcK1G5GgwJB6oUEdcLUcks/Grt+TD++fP/PNIrrzbyu7Y2aGnMiNyZ21ySqkJ70AyM5A8TLXRsR2EWlIWaXo8HL6lR0MKGIJgLM/zv2TKcgn5Az6OtQohsRkTcx2BMOU5vgnyqN4lk2ASFsKIzG/Hb4KQxbEWDuT5dM6XKbMIywwKb+KdCc4QWQAiPhDm8J2DSWoACOEcodr1zTqBHMaIXCMLWrVt0OozrDcO8Og61Qmkdv0F4g3P2YR4dNObdt1r556nAzIiM2VfHxPvMhOCLQQexEwYIF5ychpYncInUICsQHTNrIUUSzaLIL9ISchpcvI4Tt7R4bHjhDKltM2J7sHvgJ3y1Fj3s0Ib2BRLRbwpX0F0AWpp72rEc7aqTvAn8b4qju2HTjbNoH3D4nl35gv2TxL7tGmKfqtgN1vGkf8S1I6Odaawsp1eKsIEYOvi60QghCZp0duDshMfxFajaMRECzVVqqNbZOfPWZIg0JYMyxMvKDQ4fhUcritZxKCheUBeNdo6E3YxW0LnLaZGpHl/TZhlC+YKOY5kz+zpnFcANqjvSrupRGXufu8tdzmgBg9NkDbPU7y6RLnmLEAN7eHRU7piSsHSrWNjrEUm1e4xtCtSS9PtUK3jx8dqVNoO1Zz2I/m0w0y3ILRXkc6A7dZ3l2K6JnX2Wjkdhfhlt+7fXr32LUyIhxTd88i1brA2FuTAGQyC72IsON63MZgzxWMw9kZ/A7eJUV1PX3j1cDcmEv//1uOOiL37rbcUD9xW6p6l4R1LX0i2evmnG+iAYIdtlf4g3LdEil2xdYkUnTgi0UIj+AJktXmeuGD6svBp+9PPn4DhyyaE+xBUELpZ2QStbGYq1hXZeK02osqkU4s5WBYhO2ep5TELLb4OwZj8i+CWiQxNzuUCopm6ymyS2TNjQC7Eun1fn+7On2/RTcz+VZJP+79xBYTJ8QpwpT5mXEQ17mm/s7eFcI1SygVR4RcRhluu60iXWj0yUEnfBBJQTmw3IBOBwcyVCtg9bMe2n8NNxvwJZ7gyZZvB4qREEjC50ZaYoO3R5HP/XKj76/L+N3TG4ibsDAAA"; }
        }
    }
}
